config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :messages

  get '/query/:ticker', to: 'quotes#query', defaults: { format: :json }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord

  ApiKey = "PUDO6FISMN2FU948"

  def self.get(ticker, date)
    quote = find_most_recent(ticker, date)
    if quote.nil?
      Quote.fetch(ticker)
      quote = find_most_recent(ticker, date)
    end
    quote
  end

  def self.find_most_recent(ticker, date)
    Quote.where("ticker = ? and date <= ?", ticker, date).order(date: :desc).first
  end

  def self.fetch(ticker)

    # Fetch daily quotes from AlphaAdvantage
    url = "https://www.alphavantage.co/query"
    begin
      response = RestClient.get url,
                                :content_type => :json,
                                :params => {
                                  :function => "TIME_SERIES_DAILY_ADJUSTED",
                                  :symbol => ticker,
                                  :apikey => ApiKey}
      json = JSON.parse(response)
      ts_data = json["Time Series (Daily)"]

      unless ts_data.nil?
        ts_data.keys.each do |date|
          data = ts_data[date]

          q = Quote.new do |q|
            q.ticker = ticker
            q.date = date
            q.open = data["1. open"]
            q.high = data["2. high"]
            q.low = data["3. low"]
            q.close = data["4. close"]
            q.adjusted_close = data["5. adjusted close"]
            q.volume = data["6. volume"]
            q.dividend = data["7. dividend amount"]
            q.split_coefficient = data["8. split coefficient"]
          end
          q.save
        end
      else
        Quote.blacklist(ticker)
      end
    rescue RestClient::ServiceUnavailable
      # Log something here
      print "Service Unavailable: %s" % url
    end
  end

  # Create a quote with null values
  def self.blacklist(ticker)
    q = Quote.new do |q|
      q.ticker = ticker
      q.date = Date.today
    end
    q.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :body)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /query/:ticker?:date=?
  def query
    @quote = Quote.get(params[:ticker], params[:date])
    unless @quote.nil?
      render json: @quote.to_json
    else
      render nothing: true, :status => 404
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:ticker, :date, :open, :high, :low, :close, :adjusted_close, :volume, :dividend, :split_coefficient)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odyssey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/quotes/_form.html.erb
<%= form_for(quote) do |f| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %>
    <%= f.text_field :ticker %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :open %>
    <%= f.text_field :open %>
  </div>

  <div class="field">
    <%= f.label :high %>
    <%= f.text_field :high %>
  </div>

  <div class="field">
    <%= f.label :low %>
    <%= f.text_field :low %>
  </div>

  <div class="field">
    <%= f.label :close %>
    <%= f.text_field :close %>
  </div>

  <div class="field">
    <%= f.label :adjusted_close %>
    <%= f.text_field :adjusted_close %>
  </div>

  <div class="field">
    <%= f.label :volume %>
    <%= f.number_field :volume %>
  </div>

  <div class="field">
    <%= f.label :dividend %>
    <%= f.text_field :dividend %>
  </div>

  <div class="field">
    <%= f.label :split_coefficient %>
    <%= f.text_field :split_coefficient %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Date</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Adjusted close</th>
      <th>Volume</th>
      <th>Dividend</th>
      <th>Split coefficient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.ticker %></td>
        <td><%= quote.date %></td>
        <td><%= quote.open %></td>
        <td><%= quote.high %></td>
        <td><%= quote.low %></td>
        <td><%= quote.close %></td>
        <td><%= quote.adjusted_close %></td>
        <td><%= quote.volume %></td>
        <td><%= quote.dividend %></td>
        <td><%= quote.split_coefficient %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @quote.ticker %>
</p>

<p>
  <strong>Date:</strong>
  <%= @quote.date %>
</p>

<p>
  <strong>Open:</strong>
  <%= @quote.open %>
</p>

<p>
  <strong>High:</strong>
  <%= @quote.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @quote.low %>
</p>

<p>
  <strong>Close:</strong>
  <%= @quote.close %>
</p>

<p>
  <strong>Adjusted close:</strong>
  <%= @quote.adjusted_close %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @quote.volume %>
</p>

<p>
  <strong>Dividend:</strong>
  <%= @quote.dividend %>
</p>

<p>
  <strong>Split coefficient:</strong>
  <%= @quote.split_coefficient %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>